version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map the backend service to localhost:3000
    environment:
      DB_HOST: ${DB_HOST}  # Service name of the MongoDB container
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - mongo
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512m  # Limit memory usage for MongoDB

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"  # Map the frontend service to localhost:4200
    depends_on:
      - backend
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512m  # Limit memory usage for MongoDB

  mongo:
    image: mongo:6.0
    container_name: mongodbContainer
    ports:
      - "27017:27017"  # Expose MongoDB on localhost:27017
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512m  # Limit memory usage for MongoDB

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"  # Expose Mongo Express on localhost:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_SERVER: mongo  # Host name of the MongoDB container
    depends_on:
      - mongo
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512m  # Limit memory usage for MongoDB

networks:
  app-network:
    driver: bridge
